dgs:
  graphql:
    schema-locations:
    - classpath*:graphql/**/schema.graphqls
    graphiql:
      enabled: true

logging:
  level:
    com.netflix: DEBUG

spring:
  graphql:
    websocket:
      path: /subscriptions